names = [
    "John Smith",
    "Jane Johnson",
    "Michael Williams",
    "Emily Brown",
    "William Jones",
    "Olivia Miller",
    "James Davis",
    "Sophia Garcia",
    "Benjamin Rodriguez",
    "Ava Wilson",
    "Liam Martinez",
    "Isabella Anderson",
    "Ethan Taylor",
    "Mia Thomas",
    "Alexander Hernandez",
    "Emma Moore",
    "Noah Martin",
    "Oliver Jackson",
    "Charlotte Thompson",
    "Amelia White",
]
